### ISSUE TITLE
Support for 10x10 boxes

### ISSUE THREAD

**Issue by t3chbg** [dr01d3r/redcap-em-orca-specimen-tracking#1]
Hi Chris and Leila - forst off thank you for awesome module our lab teams are quite excited about it and currently testing it in my development enviroment. 
The reason for my post - Is it possible to support 10x10 boxes? We only carry 10x10 and have approx 400 boxes. The labs won't be able to use 9x9 box size and this would railroad us from introducing ORCA Specimen tracking into production.

**Comment by dr01d3r** [comment]
Hi @t3chbg!

I will talk with Leila about getting this added.  I don't think it would be much effort.  Additionally, and I should've updated this repo to note the change, but the new GitHub repository for the version of the module that's officially in the REDCap Repo is here.

https://github.com/dr01d3r/redcap-em-orca-specimen-tracking

**Comment by dr01d3r** [comment]
Fixed with the v1.0.1 release #2
